// app/layout.js
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "./provider";
import { ThemeProvider } from "next-themes";
import { NotificationProvider } from "../context/NotificationContext";
import NotificationBanner from "../components/NotificationBanner";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "EZZY Blog",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <NotificationProvider>
            {/* <NotificationBanner /> */}
            <ThemeProvider attribute="class">{children}</ThemeProvider>
          </NotificationProvider>
        </Providers>
      </body>
    </html>
  );
}
